package scripts.tearsofguthix;

/**
 * Created by Chris on 2/19/2018.
 */
public enum State {
    OPENING_BANK, JUNA_CHAT, TALKING_TO_JUNA, CLIMBING_DOWN_ROCKS, WALKING_TO_NORTHERN_ROCKS, COLLECTING_IDLE, COLLECTING_TEARS, JUNA_CHAT_COLLECT_TEARS, TELEPORTING_TO_TEARS_OF_GUTHIX, DEPOSITING_ALL, WITHDRAWING_GAMES_NECKLACE, UNEQUIPPING_WEAPON_AND_SHIELD, CLIMBING_UP_NORTH_ROCKS, WALKING_TO_STEPPING_STONE, ENTERING_TEARS_CAVE, CROSSING_STEPPING_STONES, CROSSING_CHASM, CREATING_BOWL, MINING_MAGIC_STONE, WITHDRAWING_PICKAXE, WITHDRAWING_CHISEL, WITHDRAWING_BULLSEYE_LANTERN, WITHDRAWING_SAPPHIRE_LANTERN, WITHDRAWING_SAPPHIRE, CLOSING_BANK, CREATING_SAPPHIRE_LANTERN, LIGHTING_LANTERN, EXTINGUISHING_BULLSEYE_LANTERN, WALKING_TO_JUNA, CANCELLING_COLLECTION, WITHDRAWING_TINDERBOX, WALKING_TO_SOUTHERN_ROCKS, CLOSING_QUEST_COMPLETE_INTERFACE, STORY_JUNA, WALKING_TO_BANK
}
