package scripts.clientofkourend;

public enum State {
	USING_FEATHER_ON_ENCHANTED_SCROLL, WALKING_TO_BANK, OPENING_BANK, WITHDRAWING_FEATHER, WITHDRAWING_ENCHANTED_SCROLL, WALKING_TO_QUEST_START, CHAT_VEOS_1, TALKING_TO_VEOS, CHAT_PISCARILIUS, TALKING_TO_PISCARILIUS_STORE_OWNER, WALKING_TO_PISCARILIUS_STORE, CHAT_HOSIDIUS, TALKING_TO_HOSIDIUS_STORE_OWNER, WALKING_TO_HOSIDIUS_STORE, CHAT_SHAYZIEN, TALKING_TO_SHAYZIEN_STORE_OWNER, WALKING_TO_SHAYZIEN_STORE, CHAT_LOVAKENGJ, TALKING_TO_LOVAKENGJ_STORE_OWNER, WALKING_TO_LOVAKENGJ_STORE, CHAT_ARCEUUS, TALKING_TO_ARCEUUS_STORE_OWNER, WALKING_TO_ARCEUUS_STORE, CHAT_VEOS_2, WITHDRAWING_ORB, ACTIVATING_ORB, WALKING_TO_DARK_ALTAR, CHAT_VEOS_3, CHOOSING_HOUSE_FAVOR, USING_FIRST_LAMP, USING_SECOND_LAMP, LOGGING_IN, DEPOSITING_ALL, WITHDRAWING_COINS, BUYING_FEATHER, OPENING_SHOP, WALKING_TO_FISHING_STORE, CLOSING_BANK, CLOSING_QUEST_COMPLETE_INTERFACE

}
